### ISSUE TITLE
ASUM Method BUG when editing value

### ISSUE THREAD

**Issue by PedroNeves21141** [rezo-labs/directus-extension-computed-interface#33]
Hi,when I change the price value, for some reason, the final price is the product price twice but when I complete the item and return to edit, it changes to the right value as shown in the following video

https://user-images.githubusercontent.com/73717899/226587491-fe351580-c536-4058-ac4b-28b40319b5c5.mp4

![image](https://user-images.githubusercontent.com/73717899/226587590-82d2119a-46b2-4976-af2b-de867cd92625.png)

**Comment by hermesalvesbr** [comment]
Maybe fixed with this: https://github.com/rezo-labs/directus-extension-computed-interface/pull/8

**Comment by PedroNeves21141** [comment]
I still don't understand what to do to fix this

**Comment by PedroNeves21141** [comment]
I still don't understand what to do to fix this
What i can do to fix this?

**Comment by duydvu** [comment]
Hi @PedroNeves21141, thanks for your report.
I have found the issue and fixed it in version 1.5.0
Please let me know if the problem still exists after upgrading to the new version.
